export const UPLOAD_NAVIGATION = 'UPLOAD_NAVIGATION';
export const UPLOAD_CATEGOTIES = 'UPLOAD_CATEGOTIES';
export const HIDE_MODAL = 'HIDE_MODAL';
export const SHOW_MODAL = 'SHOW_MODAL';
export const PUSH_USEEFFECT_UPDATE = 'PUSH_USEEFFECT_UPDATE';//обновляє картки навігації в адмінці
export const UPLOAD_CATEGIRIES = 'UPLOAD_UPLOAD_CATEGIRIES';
export const TRANSMIT_EDIT_PAGE_DATA = 'TRANSMIT_EDIT_PAGE_DATA';//преедаєм дані зв ибраної картки для редагування в едітор
export const TRANSMIT_EDIT_PAGE_NAME = 'TRANSMIT_EDIT_PAGE_NAME';//преедаєм вид сторінки для редагування в едітор
export const LOGO_CHANGE = 'LOGO_CHANGE';//преедаєм вид сторінки для редагування в едітор;
export const SHOW_MENU = 'SHOW_MENU';//показуэмо меню навыгыцыъ в адаптивы
export const HIDE_MENU = 'HIDE_MENU';//ховає меню навыгыцыъ в адаптивы